services:
  nginx:
    image: nginx:1-alpine
    restart: unless-stopped
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./frontend/build:/data/www
    ports:
      - 80:80

  node-backend:
    image: node:16-alpine
    restart: unless-stopped
    working_dir: /home/node/app
    environment:
      - PORT=4000
      - SESSION_SECRET=uiyHB^&*Cg^&*F#^doy8bxyzGFC^
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=awt_project
      - REDIS_URL=redis:6379
    volumes:
      - ./backend:/home/node/app
    command: sh -c "npm i && npm run dev"
    depends_on:
      - mongo
      - redis

  node-frontend:
    image: node:16-alpine
    restart: unless-stopped
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    command: sh -c "npm i && npm run dev"
    ports:
      - 35729:35729
    depends_on:
      - node-backend

  mongo:
    image: mongo:4
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
